version: 2
updates:
- package-ecosystem: npm
  directory: "/"
  schedule:
    interval: daily
    time: "21:00"
  open-pull-requests-limit: 10
  versioning-strategy: increase
  ignore:
  - dependency-name: ytsr
    versions:
    - 3.2.3
    - 3.3.0
    - 3.3.1
    - 3.4.0
    - 3.4.1
  - dependency-name: ytpl
    versions:
    - 2.1.0
    - 2.1.1
  - dependency-name: ioredis
    versions:
    - 4.20.0
    - 4.22.0
    - 4.23.0
    - 4.24.2
    - 4.24.3
    - 4.24.4
    - 4.24.5
    - 4.24.6
    - 4.25.0
    - 4.26.0
  - dependency-name: discord.js
    versions:
    - 12.5.2
  - dependency-name: ffmpeg-static
    versions:
    - 4.2.8
  - dependency-name: socket.io
    versions:
    - 3.1.0
    - 3.1.2
    - 4.0.0
  - dependency-name: discord-ytdl-core
    versions:
    - 5.0.1
